version: "3.7"

services:
  mongo:
    image: mongo:4.1.13-bionic
    restart: always
    volumes:
      - /data/mongodb/:/var/lib/mongodb:rw
    ports:
      - "63017:27017"
    networks:
      mongo:
        aliases:
          - mongo
  blogdb:
    image: mysql:5.7
    volumes: # 数据卷，映射本地文件夹
      - /data/mysql/blogdb:/var/lib/mysql
    ports: # 如果不写端口映射的话，外部无法连接该mysql（下方WordPress连接没问题）
      - "63018:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Xeroxes6136;cobras"
      MYSQL_DATABASE: blogdb
      MYSQL_USER: blogdb
      MYSQL_PASSWORD: blogdb
    networks:
      blogdb:
        aliases:
          - blogdb
networks:
  mongo:
    name: mongo
  blogdb:
    name: blogdb
