version: "3.7"

services:
  db:
    image: mysql:5.7
    container_name: blog_db
    volumes: # 数据卷，映射本地文件夹
      - /data/blog/mysql:/var/lib/mysql
    ports: # 如果不写端口映射的话，外部无法连接该mysql（下方WordPress连接没问题）
      - "55001:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Xeroxes6136;cobras"
      MYSQL_DATABASE: blogdb
      MYSQL_USER: blogdb
      MYSQL_PASSWORD: blogdb
     networks:
       blog_net:
         aliases:
           - blogdb
  blog:
    image: wordpress:latest
    container_name: blog_ilaipi
    volumes:
      - /data/blog/wp:/var/www/html
    ports:
      - "55002:80"
    depends_on:
      - db
    restart: always
    privileged: true
    environment:
      # 可以直接使用 上方 service 名 + 端口来获得链接
      WORDPRESS_DB_HOST: blogdb:3306
      WORDPRESS_DB_NAME: blogdb
      WORDPRESS_DB_USER: blogdb
      WORDPRESS_DB_PASSWORD: blogdb
      # 定义域名
      WORDPRESS_CONFIG_EXTRA: "define('WP_HOME','https://www.ilaipi.top'); define('WP_SITEURL','https://www.ilaipi.top');"
    networks:
      blog_net:
        aliases:
          - blog

networks:
  blog_net:
    name: blog_net
