version: "3.7"

services:
  ilaipi:
    image: akyakya/jd_scripts
    restart: always
    volumes:
      - ./my_crontab_list.sh:/scripts/docker/my_crontab_list.sh
      - ./logs:/scripts/logs
    tty: true
    environment:
      - JD_COOKIE=${ILAIPI_JD}
      - PUSH_KEY=${ILAIPI_SERVER_CHAIN}
      - CRONTAB_LIST_FILE=my_crontab_list.sh
    command:
      - /bin/sh
      - -c
      - |
        crontab /scripts/docker/my_crontab_list.sh
        crond
        git -C /scripts/ pull
        node
  laopo:
    image: akyakya/jd_scripts
    restart: always
    volumes:
      - ./my_crontab_list.sh:/scripts/docker/my_crontab_list.sh
      - ./laopo-logs:/scripts/logs
    tty: true
    environment:
      - JD_COOKIE=${LAOPO_JD}
      - PUSH_KEY=${ILAIPI_SERVER_CHAIN}
      - CRONTAB_LIST_FILE=my_crontab_list.sh
    command:
      - /bin/sh
      - -c
      - |
        crontab /scripts/docker/my_crontab_list.sh
        crond
        git -C /scripts/ pull
        node
